// flow-typed signature: cac370087b290813dc10e84834e8792a
// flow-typed version: <<STUB>>/koa-combine-routers_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-combine-routers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-combine-routers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-combine-routers/index' {
  declare module.exports: $Exports<'koa-combine-routers'>;
}
declare module 'koa-combine-routers/index.js' {
  declare module.exports: $Exports<'koa-combine-routers'>;
}
